<a href="https://colab.research.google.com/github/Sathishs2004/Next-Word-Prediction-RNN/blob/main/next_word_prediction_smallData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## import libraries

In [55]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## create DataSet

In [69]:
data = [
"I love machine learning",
"I love deeplearning",
"Deep learning is amazing",
"Machine learning is powerful",
"Artificial intelligence is the future"
]

## Tokenization

In [57]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data)

total_words = len(tokenizer.word_index) + 1
print(total_words)

13


## Create Input Sequences

In [58]:
input_sequences = []

for line in data:
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)

        print(token_list)
        print(n_gram)
        print()

[3, 4, 5, 1]
[3, 4]

[3, 4, 5, 1]
[3, 4, 5]

[3, 4, 5, 1]
[3, 4, 5, 1]

[3, 4, 6, 1]
[3, 4]

[3, 4, 6, 1]
[3, 4, 6]

[3, 4, 6, 1]
[3, 4, 6, 1]

[6, 1, 2, 7]
[6, 1]

[6, 1, 2, 7]
[6, 1, 2]

[6, 1, 2, 7]
[6, 1, 2, 7]

[5, 1, 2, 8]
[5, 1]

[5, 1, 2, 8]
[5, 1, 2]

[5, 1, 2, 8]
[5, 1, 2, 8]

[9, 10, 2, 11, 12]
[9, 10]

[9, 10, 2, 11, 12]
[9, 10, 2]

[9, 10, 2, 11, 12]
[9, 10, 2, 11]

[9, 10, 2, 11, 12]
[9, 10, 2, 11, 12]



## Padding

In [59]:
max_len = max(len(x) for x in input_sequences)

input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_len,
    padding='pre'
)
print(input_sequences)

[[ 0  0  0  3  4]
 [ 0  0  3  4  5]
 [ 0  3  4  5  1]
 [ 0  0  0  3  4]
 [ 0  0  3  4  6]
 [ 0  3  4  6  1]
 [ 0  0  0  6  1]
 [ 0  0  6  1  2]
 [ 0  6  1  2  7]
 [ 0  0  0  5  1]
 [ 0  0  5  1  2]
 [ 0  5  1  2  8]
 [ 0  0  0  9 10]
 [ 0  0  9 10  2]
 [ 0  9 10  2 11]
 [ 9 10  2 11 12]]


## Split X and y

In [60]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)
print(y)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## LSTM Model

In [61]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(total_words,100,input_length=max_len-1),
    tf.keras.layers.LSTM(200),
    tf.keras.layers.Dense(total_words,activation='softmax')
])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## Compile Model

In [62]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

## Train Model

In [63]:
history = model.fit(
    X,
    y,
    epochs=200,
    verbose=1
)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0625 - loss: 2.5630
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.3750 - loss: 2.5508
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 2.5382
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 2.5247
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.4375 - loss: 2.5099
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.3750 - loss: 2.4933
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3750 - loss: 2.4742
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3125 - loss: 2.4520
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.3125 - loss: 2.4260
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3125 - loss: 2.3952
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.2500 - loss: 2.3589
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.2500 - lo

## Save Model

In [64]:
model.save("next_word_prediction.keras")

## Predict Next Word using python


In [72]:
seed_text = "Machine learning is"

# Convert to sequence
token_list = tokenizer.texts_to_sequences([seed_text])[0]

# Pad sequence
token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

# Predict
predicted = np.argmax(model.predict(token_list), axis=-1)

# Find corresponding word
for word, index in tokenizer.word_index.items():
    if index == predicted:
        print(word)
        break

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
powerful
